const fbLight = {
  primary: "#1877f2", //Links buttons
  primaryHover: "#166FE5", //Links buttons
  buttonCreateNew: "#42B72A",
  loginBg: "#F0F2F5",
  commentBg: "#F0F2F5",
  activeMenuBg: "#e7f3ff",
  inactiveMenuText: "#e7f3ff",
  inputPlaceHolderTextColor: "#65676B",
  inputBg: "#f0f2f5",
  inputHoverBg: "#e4e6e9", //secondary btn bg
  borderColor: "#CED0D4",
  shadow: "#CED0D2",
  cardTextPrimary: "#050505",
  cardTextSecondary: "#65676B",
  navBarIcon: "#65676B",
  navBarRigtIconsPaddingBg: "#E4E6EB",
};

export const light = {
  id: "light",
  primary: "#6200ee",
  tertiary: "#3700b3",
  sqrBtnHover: "#500b94",
  danger: "#FFCCBC",
  loginError: "#e21010",
  active: "#42B72A",
  activeHover: "#3db027",
  activeUser: "#6201ee3b",
  itemCardDanger: "#FFE0B2",
  bg: "#F0F2F5",
  shadow: "rgba(0, 0, 0, 0.2)",
  cardBg: "#ffff",
  border: "#CED0D4",
  cardContainerBg: "#fff",
  cardBgSummary: "#fff",
  text: fbLight.cardTextPrimary,
  textLight: "#fff",
  inputBg: "#f0f2f5",
  inputBorder: fbLight.borderColor,
  inputPlaceHolderTextColor: "#65676B",
  smBtnText: fbLight.navBarIcon,
  smBtnBg: fbLight.navBarRigtIconsPaddingBg,
  smBtnHoverBg: fbLight.inputHoverBg,
  smBtnCheckedBg: fbLight.buttonCreateNew,
  bigBtnShadow: fbLight.shadow,
  fbLight,
};

const fbDark = {
  primary: "#1877f2", //Links buttons
  primaryHover: "#166FE5", //Links buttons
  buttonCreateNew: "#42B72A",
  loginBg: "#18191A",
  commentBg: "#3A3B3C",
  activeMenuBg: "#242526",
  inactiveMenuText: "#B0B3B8",
  inputPlaceHolderTextColor: "#B0B3B8",
  inputBg: "#3A3B3C",
  inputHoverBg: "#4E4F50", //secondary btn bg
  borderColor: "#393A3B",
  shadow: "#3e4042",
  cardTextPrimary: "#E4E6EB",
  cardTextSecondary: "#B0B3B8",
  navBarIcon: "#B0B3B8",
  navBarRigtIconsPaddingBg: "#3A3B3C",
};

export const dark = {
  id: "dark",
  primary: "#935ce2",
  tertiary: "#6d24b5",
  sqrBtnHover: "#500b94",
  danger: "#751f0a",
  loginError: "#ff5b5bf5",
  active: "#42B72A",
  activeHover: "#3db027",
  activeUser: "#8955d447",
  itemCardDanger: "#754805",
  bg: "#121212",
  shadow: "#0e0e0e",
  cardBg: "#222222",
  border: "#2c2c2c",
  cardContainerBg: "#1e1e1e",
  cardBgSummary: "#242526",
  text: fbDark.cardTextPrimary,
  textLight: "#e5e5e5",
  inputBg: "#343434",
  inputBorder: fbDark.borderColor,
  inputPlaceHolderTextColor: "#B0B3B8",
  smBtnText: fbDark.navBarIcon,
  smBtnBg: fbDark.navBarRigtIconsPaddingBg,
  smBtnHoverBg: fbDark.inputHoverBg,
  smBtnCheckedBg: fbDark.buttonCreateNew,
  bigBtnShadow: fbDark.shadow,
  fbDark,
};
